### PR TITLE
API interface update

### PR DESCRIPTION
**Pull request by leonhard-s**
See https://github.com/auto-pl/apl-api/pull/5.

### CODE REVIEW

**Comment by SMC242** [comment]
Please add a JSDoc comment as `code` doesn't describe itself

[salt.png](https://cdn.discordapp.com/attachments/797902824267972688/840265046323757117/Screenshot_20210507-1726212.png)
I just wanted to post this :D

**Comment by leonhard-s** [comment]
Curious what style of comment VS Code will accept as a propery-specific and which it won't.
```ts
/** This works */
a: number;
/**
 * So does this
 */
 b: number
/** Amazingly, so does this */ c: number;
d: number; /** But this does not*/
```

:potato:

**Comment by SMC242** [comment]
JSDoc is meant to look like this:
```js
/**
 * Hello, this function likes bread.
 * @the_first_arg BreadType The bread to feed it.
 * @le_sauce SauceType The sauce for the bread.
 * @pet_name string | undefined The name for your brand new bread monster
 * @returns BreadMonster Your new pet UmU
 * @throws 'Lonely' Please give your pet attention
*/
```
[Here's the list of @things ](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html)

**Comment by leonhard-s** [comment]
I am familiar with the function documentation syntax, but it is not applicable or helpful here. The `@property` or `@prop` fields are not honoured by VSC for the interface or field IntelliSense and generating HTML documentation for an API your App is consuming is a silly prospect.

All non-obvious fields are documented in the API interface definition. Once the API has reached a more mature state (i.e. once I confirmed that it covers the basic uses cases without major bottlenecks), there will be a full documentation of all API endpoints and response fields hosted alongside the API as well.

If you want this documentation replicated in TS in a format that is not thoroughly used anywhere else in your application, you may be better off adding that yourself to match your preferences.

**Comment by SMC242** [comment]
Ohhh right
```ts
/**
 * This is yo mama
*/
interface YoMama {
  /**
   * The name of yo mama
  */
  readonly name: string;
}
```
You put the comment on each member for interfaces.

As for whether this should be commented, I comment things that aren't self-explanatory by the name. I don't understand what this member is meant to be, so it should have a comment. Nothing thorough, just a quick explanation.

**Pull request merged**
